# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sms-call-automation

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
    CONNECTION_STRING: ${{ vars.CONNECTION_STRING }}
    ACS_RESOURCE_PHONE_NUMBER: ${{ vars.ACS_RESOURCE_PHONE_NUMBER }}
    COGNITIVE_SERVICES_ENDPOINT: ${{ vars.COGNITIVE_SERVICES_ENDPOINT }}
    REDIS_CONNECTION_STRING: ${{ vars.REDIS_CONNECTION_STRING }}
    PUBLIC_URL: ${{ vars.PUBLIC_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sms-call-automation'
          slot-name: 'Production'
          package: .

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2B86BA473B3841CEA5E3132C4FE11B6C }}
